// Visual theme matching the Holocron design canvas (dark, kyber-blue accent).
import { EditorView } from "@codemirror/view";
import { HighlightStyle } from "@codemirror/language";
import { tags as t } from "@lezer/highlight";
import { MONO_FONT, UI_FONT } from "./platform.js";

// Colours, fonts and sizes come from CSS custom properties that Swift sets
// (see Theme.cssVariables); the fallbacks match the dark theme.
const v = (name, fallback) => `var(--hc-${name}, ${fallback})`;
const MONO = MONO_FONT;

const c = {
  bg: v("bg", "#0F1115"),
  text: v("text", "#D8DBE0"),
  strong: v("strong", "#F2F4F7"),
  muted: v("muted", "#8A919D"),
  faint: v("faint", "#6B7280"),
  quote: v("quote", "#C9CDD4"),
  accent: v("accent", "#5AB4FF"),
  accentText: v("accent-text", "#9CCFFF"),
  accentSoft: "rgba(var(--hc-accent-rgb, 90, 180, 255), 0.14)",
  selection: "rgba(var(--hc-accent-rgb, 90, 180, 255), 0.28)",
  border: v("border", "#23272F"),
  strongBorder: v("strong-border", "#343A45"),
  raised: v("raised", "#161A20"),
  chip: v("chip", "#1E222A"),
  panel: v("panel", "#1A1D23"),
};

export const holocronTheme = EditorView.theme(
  {
    "&": { color: c.text, backgroundColor: c.bg, height: "100%", fontSize: v("font-size", "16px") },
    "&.cm-focused": { outline: "none" },
    ".cm-scroller": { fontFamily: v("font", UI_FONT), lineHeight: "1.65", padding: "28px 0 35vh" },
    ".cm-content": {
      maxWidth: `calc(${v("line-width", "720px")} + 64px)`,
      width: "100%",
      margin: "0 auto",
      padding: "0 32px",
      boxSizing: "border-box",
      caretColor: c.accent,
    },
    ".cm-line": { padding: "0" },
    ".cm-cursor, .cm-dropCursor": { borderLeft: `2px solid ${c.accent}` },
    "&.cm-focused > .cm-scroller > .cm-selectionLayer .cm-selectionBackground, .cm-selectionBackground, .cm-content ::selection":
      { backgroundColor: `${c.selection} !important` },
    ".cm-placeholder": { color: c.faint },

    // Headings
    ".cm-h": { color: c.strong },
    ".cm-h1": { fontSize: "2.125em", lineHeight: "1.25", fontWeight: "700", letterSpacing: "-0.01em", paddingTop: "10px" },
    ".cm-h2": { fontSize: "1.44em", lineHeight: "1.3", fontWeight: "650", paddingTop: "14px" },
    ".cm-h3": { fontSize: "1.19em", lineHeight: "1.35", fontWeight: "650", paddingTop: "10px" },
    ".cm-h4": { fontSize: "1.06em", fontWeight: "650", paddingTop: "8px" },
    ".cm-h5": { fontSize: "0.94em", fontWeight: "650", paddingTop: "6px" },
    ".cm-h6": { fontSize: "0.88em", fontWeight: "650", color: c.muted, paddingTop: "6px" },
    ".cm-formatting": { color: c.faint },
    ".cm-formatting-header": { fontFamily: MONO, fontWeight: "400", fontSize: "0.78em" },

    // Links & tags
    ".cm-wikilink, .cm-md-link": { color: c.accent, cursor: "pointer" },
    ".cm-wikilink:hover, .cm-md-link:hover": { textDecoration: "underline", textUnderlineOffset: "3px" },
    ".cm-tag": {
      color: c.accentText,
      backgroundColor: c.accentSoft,
      borderRadius: "10px",
      padding: "1px 7px",
      fontSize: "0.88em",
    },

    // Inline code & code blocks
    ".cm-inline-code": {
      fontFamily: MONO,
      fontSize: "0.86em",
      backgroundColor: c.chip,
      borderRadius: "4px",
      padding: "1px 4px",
    },
    ".cm-codeblock": {
      fontFamily: MONO,
      fontSize: "13.5px",
      lineHeight: "1.7",
      backgroundColor: c.raised,
      borderLeft: `1px solid ${c.border}`,
      borderRight: `1px solid ${c.border}`,
      padding: "0 16px !important",
    },
    ".cm-codeblock-first": { borderTop: `1px solid ${c.border}`, borderRadius: "8px 8px 0 0", paddingTop: "8px !important", marginTop: "4px" },
    ".cm-codeblock-last": { borderBottom: `1px solid ${c.border}`, borderRadius: "0 0 8px 8px", paddingBottom: "8px !important", marginBottom: "4px" },
    ".cm-codeblock-first.cm-codeblock-last": { borderRadius: "8px" },
    ".cm-codeblock-fence": { color: c.faint, fontSize: "11.5px" },

    // Quotes & callouts
    ".cm-blockquote": { borderLeft: `3px solid ${c.strongBorder}`, paddingLeft: "14px !important", color: c.quote },
    ".cm-callout": {
      backgroundColor: "rgba(var(--callout), 0.10)",
      borderLeft: "1px solid rgba(var(--callout), 0.32)",
      borderRight: "1px solid rgba(var(--callout), 0.32)",
      padding: "0 16px !important",
    },
    ".cm-callout-first": { borderTop: "1px solid rgba(var(--callout), 0.32)", borderRadius: "8px 8px 0 0", paddingTop: "10px !important", marginTop: "4px" },
    ".cm-callout-last": { borderBottom: "1px solid rgba(var(--callout), 0.32)", borderRadius: "0 0 8px 8px", paddingBottom: "10px !important", marginBottom: "4px" },
    ".cm-callout-first.cm-callout-last": { borderRadius: "8px" },
    ".cm-callout-title": {
      display: "inline-flex",
      alignItems: "center",
      gap: "8px",
      fontWeight: "600",
      fontSize: "14px",
      color: "rgb(var(--callout-text))",
      marginRight: "6px",
    },
    ".cm-callout-title-text": { fontWeight: "600", fontSize: "14px", color: "rgb(var(--callout-text))" },
    ".cm-callout-icon": {
      width: "14px",
      height: "14px",
      borderRadius: "50%",
      border: "1.5px solid rgb(var(--callout-text))",
      boxSizing: "border-box",
    },

    // Lists & tasks
    ".cm-bullet": { color: c.muted, display: "inline-block", width: "0.9em" },
    ".cm-task-checkbox": {
      display: "inline-block",
      position: "relative",
      width: "16px",
      height: "16px",
      boxSizing: "border-box",
      border: `1.5px solid ${c.faint}`,
      borderRadius: "4px",
      verticalAlign: "-2px",
      marginRight: "8px",
      cursor: "pointer",
    },
    ".cm-task-checkbox:hover": { borderColor: c.accent },
    ".cm-task-checkbox.is-checked": { backgroundColor: c.accent, borderColor: c.accent },
    ".cm-task-checkbox.is-checked::after": {
      content: "''",
      position: "absolute",
      left: "4.5px",
      top: "1.5px",
      width: "4px",
      height: "8px",
      border: `solid ${c.bg}`,
      borderWidth: "0 2px 2px 0",
      transform: "rotate(45deg)",
    },
    ".cm-task-done": { color: c.muted, textDecoration: "line-through" },

    // Properties (frontmatter)
    ".cm-properties": {
      display: "flex",
      flexDirection: "column",
      gap: "4px",
      padding: "4px 0 14px",
      marginBottom: "10px",
      borderBottom: `1px solid ${c.border}`,
      fontSize: "13.5px",
      lineHeight: "1.5",
      cursor: "text",
    },
    ".cm-property": { display: "flex", alignItems: "center", gap: "14px", minHeight: "26px" },
    ".cm-property-key": {
      width: "112px",
      flexShrink: "0",
      color: c.muted,
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
    ".cm-property-value": { display: "flex", flexWrap: "wrap", alignItems: "center", gap: "6px", color: c.text, minWidth: "0" },
    ".cm-property-pill": { padding: "1px 8px", borderRadius: "10px", backgroundColor: c.chip, fontSize: "0.92em" },
    ".cm-property-empty": { color: c.faint, fontStyle: "italic" },
    ".cm-property-checkbox": { marginRight: "0", verticalAlign: "middle" },

    // Note embeds
    ".cm-embed": {
      margin: "6px 0 12px",
      border: `1px solid ${c.border}`,
      borderRadius: "8px",
      overflow: "hidden",
      backgroundColor: c.raised,
    },
    ".cm-embed-header": {
      padding: "6px 14px",
      fontSize: "12.5px",
      fontWeight: "600",
      color: c.accentText,
      borderBottom: `1px solid ${c.border}`,
      cursor: "pointer",
      fontFamily: UI_FONT,
    },
    ".cm-embed-header:hover .cm-embed-title": { textDecoration: "underline", textUnderlineOffset: "3px" },
    ".cm-embed-body": { padding: "10px 16px", maxHeight: "480px", overflowY: "auto" },
    ".cm-embed-body .cm-editor": { backgroundColor: "transparent" },
    ".cm-embed-message": { color: c.muted, fontSize: "13px", fontStyle: "italic" },

    // Focus mode: dim all but the current paragraph; room to centre any line.
    "&.cm-focus-mode .cm-scroller": { paddingTop: "40vh", paddingBottom: "50vh" },
    ".cm-dimmed, &.cm-focus-mode:not(.cm-mode-reading) .cm-content > :not(.cm-line)": { opacity: "0.28", transition: "opacity 0.2s ease-out" },
    "&.cm-focus-mode .cm-line": { transition: "opacity 0.2s ease-out" },

    // Hover previews (⌘ over a link)
    ".cm-hover-preview": {
      position: "fixed",
      zIndex: "250",
      width: "min(460px, calc(100vw - 16px))",
      boxShadow: "0 12px 32px rgba(0, 0, 0, 0.4)",
      borderRadius: "8px",
    },
    ".cm-hover-preview .cm-embed": { margin: "0", backgroundColor: c.panel, borderColor: c.strongBorder },
    ".cm-hover-preview .cm-embed-body": { maxHeight: "340px" },

    // Highlights, footnotes, comments, block ids, link definitions, HTML
    ".cm-highlight": { backgroundColor: "var(--hc-highlight, rgba(232, 193, 90, 0.32))", borderRadius: "3px", padding: "0 1px" },
    ".cm-footnote-ref": {
      color: c.accentText,
      fontSize: "0.72em",
      verticalAlign: "super",
      lineHeight: "0",
      padding: "0 2px",
      cursor: "pointer",
    },
    ".cm-footnote-def": { fontSize: "0.88em", color: c.muted },
    ".cm-footnote-def-marker": { color: c.accentText, marginRight: "6px", cursor: "pointer" },
    ".cm-comment": { color: c.faint, fontStyle: "italic" },
    ".cm-block-id": { color: c.faint, fontSize: "0.85em" },
    ".cm-link-definition": { fontSize: "0.88em", color: c.muted },
    ".cm-html-kbd": {
      fontFamily: MONO,
      fontSize: "0.82em",
      padding: "1px 6px",
      border: `1px solid ${c.strongBorder}`,
      borderBottomWidth: "2px",
      borderRadius: "4px",
      backgroundColor: c.chip,
    },
    ".cm-html-mark": { backgroundColor: "var(--hc-highlight, rgba(232, 193, 90, 0.32))", borderRadius: "3px" },
    ".cm-html-sup": { fontSize: "0.75em", verticalAlign: "super", lineHeight: "0" },
    ".cm-html-sub": { fontSize: "0.75em", verticalAlign: "sub", lineHeight: "0" },
    ".cm-html-u, .cm-html-ins": { textDecoration: "underline", textUnderlineOffset: "3px" },
    ".cm-html-b": { fontWeight: "700", color: c.strong },
    ".cm-html-i": { fontStyle: "italic" },
    ".cm-html-s, .cm-html-del": { textDecoration: "line-through", color: c.muted },
    ".cm-html-small": { fontSize: "0.85em" },
    ".cm-html-br": { display: "block", height: "0" },
    ".cm-collapsed-line": { fontSize: "1px", lineHeight: "1px", height: "1px", overflow: "hidden" },

    // Folding (callouts with + / -, <details>)
    ".cm-fold-chevron": {
      display: "inline-block",
      width: "0",
      height: "0",
      borderLeft: "5px solid transparent",
      borderRight: "5px solid transparent",
      borderTop: "6px solid currentColor",
      margin: "0 6px 2px 0",
      transition: "transform 0.12s ease",
    },
    ".cm-fold-chevron.is-folded": { transform: "rotate(-90deg)" },
    ".cm-callout-title.is-foldable, .cm-summary": { cursor: "pointer" },
    ".cm-summary": { fontWeight: "600", color: c.strong },

    // Extra checkbox states
    ".cm-task-checkbox.cm-task-cancelled": { backgroundColor: c.faint, borderColor: c.faint },
    ".cm-task-checkbox.cm-task-cancelled::after": {
      content: "''", position: "absolute", left: "3px", right: "3px", top: "6px", height: "2px",
      width: "auto", border: "none", backgroundColor: c.bg, transform: "none",
    },
    ".cm-task-checkbox.cm-task-partial": { background: `linear-gradient(135deg, ${c.accent} 50%, transparent 50%)` },
    ".cm-task-checkbox.cm-task-partial::after": { display: "none" },
    ".cm-task-checkbox.cm-task-forwarded::after, .cm-task-checkbox.cm-task-scheduled::after, .cm-task-checkbox.cm-task-important::after, .cm-task-checkbox.cm-task-question::after, .cm-task-checkbox.cm-task-star::after": {
      border: "none", transform: "none", width: "auto", height: "auto", left: "0", right: "0", top: "-2px",
      textAlign: "center", fontSize: "11px", fontWeight: "700", color: c.bg, fontFamily: UI_FONT,
    },
    ".cm-task-checkbox.cm-task-forwarded::after": { content: "'›'" },
    ".cm-task-checkbox.cm-task-scheduled::after": { content: "'‹'" },
    ".cm-task-checkbox.cm-task-important": { backgroundColor: "var(--hc-warning, #E8C15A)", borderColor: "var(--hc-warning, #E8C15A)" },
    ".cm-task-checkbox.cm-task-important::after": { content: "'!'" },
    ".cm-task-checkbox.cm-task-question::after": { content: "'?'" },
    ".cm-task-checkbox.cm-task-star::after": { content: "'★'", fontSize: "9px", top: "0" },

    // Tables
    ".cm-table-widget": { overflowX: "auto", margin: "6px 0 12px" },
    ".cm-table-widget table": { borderCollapse: "collapse", fontSize: "0.94em", minWidth: "50%" },
    ".cm-table-widget th, .cm-table-widget td": {
      border: `1px solid ${c.border}`,
      padding: "6px 12px",
      verticalAlign: "top",
      cursor: "text",
    },
    ".cm-table-widget th": { backgroundColor: c.raised, fontWeight: "600", color: c.strong, textAlign: "left" },
    ".cm-table-widget tbody tr:nth-child(even) td": { backgroundColor: "rgba(127, 127, 127, 0.04)" },
    ".cm-table-raw": { fontFamily: MONO, fontSize: "14px" },

    // Table controls (tableTools.js): a gutter on the left for row handles,
    // and + bars to the right and below. Everything appears on hover.
    ".cm-table-widget.cm-table-editable": { paddingLeft: "26px", marginLeft: "-26px", marginBottom: "0" },
    ".cm-table-frame": {
      display: "grid",
      gridTemplateColumns: "auto 22px",
      gridTemplateRows: "auto 22px",
      width: "max-content",
      minWidth: "50%",
    },
    ".cm-table-frame > table": { gridColumn: "1", gridRow: "1", width: "100%", minWidth: "0" },
    ".cm-table-editable th, .cm-table-editable td": { position: "relative" },
    ".cm-table-editable th": { paddingRight: "28px" },
    ".cm-table-control": {
      appearance: "none",
      border: "none",
      padding: "0",
      margin: "0",
      background: "transparent",
      color: c.muted,
      cursor: "pointer",
      opacity: "0",
      transition: "opacity 0.12s ease-out, background-color 0.12s ease-out",
      fontFamily: UI_FONT,
      lineHeight: "1",
    },
    ".cm-table-control:hover": { color: c.strong, backgroundColor: c.chip },
    ".cm-table-col-button": {
      position: "absolute",
      top: "50%",
      right: "5px",
      transform: "translateY(-50%)",
      width: "20px",
      height: "20px",
      borderRadius: "4px",
      fontSize: "11px",
    },
    ".cm-table-col-button::before": { content: "'▾'" },
    ".cm-table-row-button": {
      position: "absolute",
      top: "0",
      bottom: "0",
      left: "-25px",
      width: "24px",
      borderRadius: "4px",
      fontSize: "14px",
      fontWeight: "700",
      letterSpacing: "-3px",
    },
    ".cm-table-row-button::before": { content: "'⋮⋮'", marginLeft: "-3px" },
    ".cm-table-editable th:hover > .cm-table-col-button, .cm-table-editable tr:hover .cm-table-row-button": { opacity: "1" },
    ".cm-table-add": { borderRadius: "4px", fontSize: "15px" },
    ".cm-table-frame:hover > .cm-table-add": { opacity: "1" },
    ".cm-table-add-column": { gridColumn: "2", gridRow: "1", marginLeft: "4px" },
    ".cm-table-add-row": { gridColumn: "1", gridRow: "2", marginTop: "4px" },
    ".cm-table-menu": {
      position: "fixed",
      zIndex: "300",
      minWidth: "200px",
      padding: "4px",
      backgroundColor: c.panel,
      border: `1px solid ${c.strongBorder}`,
      borderRadius: "8px",
      boxShadow: "0 8px 24px rgba(0, 0, 0, 0.35)",
      fontFamily: UI_FONT,
      fontSize: "13px",
    },
    ".cm-table-menu-item": {
      display: "flex",
      alignItems: "center",
      gap: "4px",
      width: "100%",
      padding: "4px 12px 4px 4px",
      border: "none",
      borderRadius: "5px",
      background: "transparent",
      color: c.text,
      textAlign: "left",
      font: "inherit",
      cursor: "default",
    },
    ".cm-table-menu-item:hover:not(:disabled)": { backgroundColor: c.accent, color: "#fff" },
    ".cm-table-menu-item:disabled": { color: c.faint },
    ".cm-table-menu-destructive:not(:disabled)": { color: "#F87171" },
    ".cm-table-menu-check": { display: "inline-block", width: "16px", textAlign: "center", fontSize: "12px" },
    ".cm-table-menu-separator": { height: "1px", margin: "4px 8px", backgroundColor: c.border },

    // Code block label & copy button
    ".cm-code-tools": { float: "right", display: "inline-flex", gap: "8px", alignItems: "center", fontFamily: UI_FONT },
    ".cm-code-language": { fontSize: "11px", color: c.faint, textTransform: "lowercase" },
    ".cm-code-copy": {
      fontSize: "11px",
      color: c.muted,
      background: "transparent",
      border: `1px solid ${c.strongBorder}`,
      borderRadius: "5px",
      padding: "1px 8px",
      cursor: "pointer",
    },
    ".cm-code-copy:hover": { color: c.text, borderColor: c.muted },

    // Images
    // A line holding only an image or embed collapses once its syntax is
    // hidden, so the widget below it isn't preceded by a blank line.
    ".cm-line.cm-media-source": { height: "0", overflow: "hidden" },
    ".cm-image-block": { display: "flex", flexDirection: "column", gap: "8px", padding: "6px 0 10px" },
    ".cm-image": { maxWidth: "100%", height: "auto", borderRadius: "6px", alignSelf: "flex-start" },
    ".cm-image-missing": {
      fontSize: "13px",
      color: c.muted,
      border: `1px dashed ${c.strongBorder}`,
      borderRadius: "6px",
      padding: "10px 12px",
    },

    // Rules, frontmatter, tables
    ".cm-hr": { display: "inline-block", width: "100%", height: "1px", backgroundColor: c.strongBorder, verticalAlign: "middle" },
    ".cm-frontmatter": { fontFamily: MONO, fontSize: "12.5px", lineHeight: "1.7", color: c.muted },
    ".cm-frontmatter-last": { paddingBottom: "12px !important", borderBottom: `1px solid ${c.border}`, marginBottom: "8px" },
    ".cm-table": { fontFamily: MONO, fontSize: "14px" },

    // Autocomplete
    ".cm-tooltip": { backgroundColor: c.panel, border: `1px solid ${c.strongBorder}`, borderRadius: "8px", color: c.text },
    ".cm-tooltip.cm-tooltip-autocomplete": {
      padding: "4px",
      boxShadow: "0 12px 32px rgba(0, 0, 0, 0.35)",
      fontFamily: UI_FONT,
    },
    ".cm-tooltip.cm-tooltip-autocomplete > ul": { maxHeight: "18em", minWidth: "260px", fontFamily: "inherit" },
    ".cm-tooltip.cm-tooltip-autocomplete > ul > li": {
      display: "flex",
      alignItems: "baseline",
      gap: "10px",
      padding: "4px 10px",
      borderRadius: "5px",
      lineHeight: "1.5",
      fontSize: "14px",
    },
    ".cm-tooltip-autocomplete ul li[aria-selected]": { backgroundColor: `rgba(var(--hc-accent-rgb, 90, 180, 255), 0.22)`, color: c.strong },
    ".cm-completionLabel": { flex: "1", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
    ".cm-completionMatchedText": { textDecoration: "none", fontWeight: "700", color: c.accentText },
    ".cm-completionDetail": { fontStyle: "normal", fontSize: "12px", color: c.muted, marginLeft: "0" },

    // Search panel
    ".cm-panels": { backgroundColor: c.panel, color: c.text },
    ".cm-panels.cm-panels-top": { borderBottom: `1px solid ${c.strongBorder}` },
    ".cm-search": { fontFamily: UI_FONT, fontSize: "13px", padding: "8px 12px" },
    ".cm-search label": { color: c.muted },
    ".cm-textfield": {
      backgroundColor: c.bg,
      border: `1px solid ${c.strongBorder}`,
      borderRadius: "5px",
      color: c.text,
      padding: "3px 6px",
    },
    ".cm-button": {
      backgroundImage: "none",
      backgroundColor: c.chip,
      border: `1px solid ${c.strongBorder}`,
      borderRadius: "5px",
      color: c.text,
    },
    ".cm-searchMatch": { backgroundColor: "rgba(232, 193, 90, 0.25)" },
    ".cm-searchMatch.cm-searchMatch-selected": { backgroundColor: "rgba(232, 193, 90, 0.55)" },
    ".cm-panel.cm-search [name=close]": { color: c.muted },
  },
  {},
);

export const holocronHighlight = HighlightStyle.define([
  { tag: t.emphasis, fontStyle: "italic" },
  { tag: t.strong, fontWeight: "700", color: c.strong },
  { tag: t.strikethrough, textDecoration: "line-through", color: c.muted },
  { tag: t.link, color: c.accent },
  { tag: t.url, color: c.muted },
  { tag: t.processingInstruction, color: c.faint },
  { tag: t.monospace, fontFamily: MONO },
  { tag: t.quote, color: c.quote },
  { tag: t.contentSeparator, color: c.faint },
  { tag: t.labelName, color: c.accentText },
  { tag: t.meta, color: c.muted },
  { tag: t.comment, color: c.faint },
]);
